name: dev-deploy.yml
on:

  push:
    branches:
      - "dev/*"
  pull_request_review:
    types: [edited, submitted]
    branches:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: https://adb-7405605185991044.4.azuredatabricks.net
      DATABRICKS_CLIENT_ID: 0fbc6566-282b-47bf-9122-11f99addc705

    steps:
      - uses: actions/checkout@v4

      - name: Install CLI
        uses: databricks/setup-cli@main

      - run: databricks current-user me

      - run: databricks bundle validate --target dev

      - run: databricks pipelines deploy --target dev
